-- Up migration (sqlite): discard legacy optional derived resources. Before the
-- current observer filter existed, only app-http was readiness-proven. Every
-- other link can be regenerated by a future successful project start. Checkouts,
-- volumes, secrets, and operations are not represented by this projection table.
DELETE FROM project_resources
WHERE resource_id <> 'app-http';
