// Code generated by go generate; DO NOT EDIT.

import type { AddProjectResult, ConnectionEvent, DaemonStatus, HarborSnapshot } from '@/domain/harbor'
import type { HarborWireFixture } from './types'

export interface WailsAppBindings {
  AddProject(): Promise<AddProjectResult>
  OpenResource(projectId: string, resourceId: string): Promise<void>
  Snapshot(): Promise<HarborSnapshot>
  Status(): Promise<DaemonStatus>
}

export interface WailsEventPayloads {
  "harbor:connection": ConnectionEvent
  "harbor:snapshot": HarborSnapshot
}

export type WailsEventName = keyof WailsEventPayloads

export interface WailsRuntimeEvents {
  EventsOff(eventName: WailsEventName): void
  EventsOn<Name extends WailsEventName>(eventName: Name, callback: (payload: WailsEventPayloads[Name]) => void): () => void
}

export const harborWireFixture = {
  "methods": {
    "add_project": "AddProject",
    "open_resource": "OpenResource",
    "snapshot": "Snapshot",
    "status": "Status"
  },
  "events": {
    "connection": "harbor:connection",
    "snapshot": "harbor:snapshot"
  },
  "connection_payloads": {
    "connecting": {
      "state": "connecting"
    },
    "connected": {
      "state": "connected"
    },
    "disconnected": {
      "state": "disconnected"
    }
  },
  "status": {
    "state": "ready",
    "build": {
      "version": "dev",
      "revision": "fixture",
      "modified": false
    },
    "protocol": {
      "major": 1,
      "minor": 0
    },
    "capabilities": [
      "control.project-registration.v1",
      "control.v1"
    ],
    "snapshot_schema_version": 1,
    "sequence": 42
  },
  "snapshot": {
    "schema_version": 1,
    "sequence": 42,
    "captured_at": "2026-07-18T14:35:20Z",
    "projects": [
      {
        "id": "orders-api",
        "name": "Orders API",
        "path": "/workspace/apps/orders-api",
        "slug": "orders-api",
        "state": "ready",
        "favorite": true,
        "updated_at": "2026-07-18T14:33:20Z",
        "apps": [
          {
            "id": "web",
            "name": "Web",
            "state": "ready",
            "active": true,
            "required": true
          },
          {
            "id": "worker",
            "name": "Worker",
            "state": "ready",
            "active": true,
            "required": false
          }
        ],
        "services": [
          {
            "id": "mysql",
            "name": "MySQL",
            "kind": "database",
            "state": "ready",
            "owner": "compose",
            "selection": "selected",
            "required": true
          },
          {
            "id": "redis",
            "name": "Redis",
            "kind": "cache",
            "state": "ready",
            "owner": "compose",
            "selection": "selected",
            "required": false
          }
        ],
        "resources": [
          {
            "id": "application",
            "name": "Application",
            "kind": "application",
            "owner": {
              "kind": "app",
              "app_id": "web"
            },
            "url": "https://orders.test"
          },
          {
            "id": "api-reference",
            "name": "API Reference",
            "kind": "api-reference",
            "owner": {
              "kind": "app",
              "app_id": "web"
            },
            "url": "https://orders.test/swagger"
          }
        ]
      },
      {
        "id": "billing",
        "name": "Billing",
        "path": "/workspace/apps/billing",
        "slug": "billing",
        "state": "failed",
        "favorite": true,
        "updated_at": "2026-07-18T14:29:20Z",
        "apps": [
          {
            "id": "web",
            "name": "Web",
            "state": "ready",
            "active": true,
            "required": true
          }
        ],
        "services": [
          {
            "id": "database",
            "name": "PostgreSQL",
            "kind": "database",
            "state": "failed",
            "owner": "compose",
            "selection": "selected",
            "required": true
          }
        ],
        "resources": []
      },
      {
        "id": "storefront",
        "name": "Storefront",
        "path": "/workspace/apps/storefront",
        "slug": "storefront",
        "state": "ready",
        "favorite": false,
        "updated_at": "2026-07-18T13:54:20Z",
        "apps": [
          {
            "id": "web",
            "name": "Web",
            "state": "ready",
            "active": true,
            "required": true
          }
        ],
        "services": [
          {
            "id": "mail",
            "name": "Mailpit",
            "kind": "mail",
            "state": "ready",
            "owner": "compose",
            "selection": "selected",
            "required": false
          }
        ],
        "resources": [
          {
            "id": "mail",
            "name": "Mailpit",
            "kind": "mail",
            "owner": {
              "kind": "service",
              "service_id": "mail"
            },
            "url": "https://mail.storefront.test"
          }
        ]
      },
      {
        "id": "reports",
        "name": "Reports",
        "path": "/workspace/apps/reports",
        "slug": "reports",
        "state": "stopped",
        "favorite": false,
        "updated_at": "2026-07-17T20:00:00Z",
        "apps": [
          {
            "id": "web",
            "name": "Web",
            "state": "stopped",
            "active": false,
            "required": true
          }
        ],
        "services": [],
        "resources": []
      }
    ],
    "operations": [
      {
        "id": "operation-42",
        "intent_id": "intent-42",
        "kind": "project.reconcile",
        "project_id": "orders-api",
        "state": "running",
        "phase": "observing",
        "requested_at": "2026-07-18T14:35:18Z",
        "started_at": "2026-07-18T14:35:19Z"
      }
    ],
    "recent_resource_ids": [
      {
        "project_id": "orders-api",
        "resource_id": "application"
      },
      {
        "project_id": "orders-api",
        "resource_id": "api-reference"
      },
      {
        "project_id": "storefront",
        "resource_id": "mail"
      }
    ]
  },
  "add_project": {
    "canceled": false,
    "registration": {
      "project": {
        "id": "inventory",
        "name": "Inventory",
        "path": "/workspace/apps/inventory",
        "slug": "inventory",
        "state": "stopped",
        "favorite": false,
        "updated_at": "2026-07-18T14:36:00Z",
        "apps": [],
        "services": [],
        "resources": []
      },
      "revision": 43,
      "created": true
    }
  },
  "terminal_operation": {
    "id": "operation-terminal",
    "intent_id": "intent-terminal",
    "kind": "project.reconcile",
    "project_id": "billing",
    "state": "failed",
    "phase": "failed",
    "problem": {
      "code": "service_unavailable",
      "message": "PostgreSQL did not become ready.",
      "retryable": true
    },
    "requested_at": "2026-07-18T14:20:00Z",
    "started_at": "2026-07-18T14:20:01Z",
    "finished_at": "2026-07-18T14:20:02Z"
  }
} satisfies HarborWireFixture
