// Code generated by forj generate --db. DO NOT EDIT.
// Run: forj generate --db
//
// This file contains accessors generated from DB_<NAME>_<KEY> environment variables.
// For example, DB_ANALYTICS_DRIVER will generate GetAnalytics().
package database

import (
	"context"
	"fmt"
	"github.com/glebarez/sqlite"
	"gorm.io/gorm"
)

type ReadinessCheck struct {
	Name  string
	Check func(context.Context) error
}

func (c *Connections) ReadinessChecks() []ReadinessCheck {
	if c == nil {
		return nil
	}
	checks := []ReadinessCheck{
		{
			Name: "db_default",
			Check: func(ctx context.Context) error {
				return c.readinessCheck(ctx, "default")
			},
		},
		{
			Name: "db_harbord",
			Check: func(ctx context.Context) error {
				return c.readinessCheck(ctx, "harbord")
			},
		},
	}
	return checks
}

func (c *Connections) readinessCheck(ctx context.Context, name string) error {
	conn, err := c.Connection(name)
	if err != nil {
		return err
	}
	sqlDB, err := conn.DB()
	if err != nil {
		return err
	}
	return sqlDB.PingContext(ctx)
}

func openDialector(driver, dsn string) (gorm.Dialector, error) {
	switch driver {
	case "sqlite", "sqlite3":
		if err := ensureSQLitePath(dsn); err != nil {
			return nil, err
		}
		return sqlite.Open(dsn), nil
	default:
		return nil, fmt.Errorf("unsupported driver %q", driver)
	}
}

// GetHarbord returns the "harbord" connection.
func (c *Connections) GetHarbord() (*gorm.DB, error) {
	return c.get("harbord")
}
