// Package trustedhttpsharness provides the strict native probe used by Harbor's
// three-project trusted-HTTPS acceptance gate.
package trustedhttpsharness

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"strings"
)

const (
	systemCurlPath          = "/usr/bin/curl"
	maximumProbeOutputBytes = 1 << 20
	maximumProbeErrorBytes  = 64 << 10
)

// Endpoint identifies one exact generated project response expected through
// Harbor's system-resolved, system-trusted ingress.
type Endpoint struct {
	// Domain is one lowercase project label beneath the reserved .test suffix.
	Domain string
	// OpenAPITitle is the project-specific title generated by GoForj.
	OpenAPITitle string
}

// Result records the exact native HTTPS identity returned for one endpoint.
type Result struct {
	// Domain is the literal system-resolved hostname sent to curl.
	Domain string
	// OpenAPITitle is the identity decoded from the generated OpenAPI document.
	OpenAPITitle string
}

// Command describes one direct process invocation without granting a shell or
// caller-selected curl options.
type Command struct {
	// Path is the absolute executable selected by the harness.
	Path string
	// Arguments are passed directly to the executable.
	Arguments []string
	// Environment is the complete sanitized process environment.
	Environment []string
}

// CommandResult retains only the bounded output required to validate a native
// HTTPS response or report a useful failure.
type CommandResult struct {
	// StandardOutput contains the bounded response body.
	StandardOutput []byte
	// StandardError contains bounded curl diagnostics.
	StandardError []byte
}

// CommandRunner executes one direct bounded command.
type CommandRunner interface {
	// Run executes command without a shell and reports process failures directly.
	Run(context.Context, Command) (CommandResult, error)
}

// ExecRunner runs the system curl process with bounded output retention.
type ExecRunner struct{}

// Probe requests every endpoint through literal HTTPS names and verifies that
// each generated project returned its own distinct OpenAPI identity.
func Probe(ctx context.Context, runner CommandRunner, endpoints []Endpoint) ([]Result, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if runner == nil {
		return nil, errors.New("trusted HTTPS probe requires a command runner")
	}
	if err := validateEndpoints(endpoints); err != nil {
		return nil, err
	}

	results := make([]Result, 0, len(endpoints))
	for _, endpoint := range endpoints {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		command := curlCommand(endpoint.Domain)
		output, err := runner.Run(ctx, command)
		if err != nil {
			return nil, fmt.Errorf(
				"request https://%s/swagger/doc.json through system DNS and trust: %w (curl stderr: %q)",
				endpoint.Domain,
				err,
				strings.TrimSpace(string(output.StandardError)),
			)
		}
		title, err := decodeOpenAPITitle(output.StandardOutput)
		if err != nil {
			return nil, fmt.Errorf("decode https://%s/swagger/doc.json: %w", endpoint.Domain, err)
		}
		if title != endpoint.OpenAPITitle {
			return nil, fmt.Errorf(
				"https://%s returned OpenAPI title %q, expected %q",
				endpoint.Domain,
				title,
				endpoint.OpenAPITitle,
			)
		}
		results = append(results, Result{Domain: endpoint.Domain, OpenAPITitle: title})
	}
	return results, nil
}

// Run executes one command with hard output bounds so an unhealthy endpoint
// cannot exhaust the acceptance worker while diagnostics are being collected.
func (ExecRunner) Run(ctx context.Context, specification Command) (CommandResult, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if specification.Path != systemCurlPath {
		return CommandResult{}, fmt.Errorf("trusted HTTPS probe executable is %q, expected %q", specification.Path, systemCurlPath)
	}
	stdout := &boundedBuffer{maximum: maximumProbeOutputBytes}
	stderr := &boundedBuffer{maximum: maximumProbeErrorBytes}
	command := exec.CommandContext(ctx, specification.Path, specification.Arguments...)
	command.Env = append([]string(nil), specification.Environment...)
	command.Stdin = nil
	command.Stdout = stdout
	command.Stderr = stderr
	err := command.Run()
	result := CommandResult{
		StandardOutput: append([]byte(nil), stdout.Bytes()...),
		StandardError:  append([]byte(nil), stderr.Bytes()...),
	}
	if stdout.overflow || stderr.overflow {
		return result, errors.New("curl output exceeded the acceptance bound")
	}
	return result, err
}

// curlCommand fixes every option that matters to the acceptance claim: the
// system resolver sees a literal name, curl uses implicit 443 and its default
// trust backend, and ambient proxy, curlrc, or CA overrides cannot help it pass.
func curlCommand(domain string) Command {
	return Command{
		Path: systemCurlPath,
		Arguments: []string{
			"--disable",
			"--fail",
			"--silent",
			"--show-error",
			"--noproxy", "*",
			"--proto", "=https",
			"--connect-timeout", "10",
			"--max-time", "30",
			"https://" + domain + "/swagger/doc.json",
		},
		Environment: nativeProbeEnvironment(),
	}
}

// nativeProbeEnvironment preserves only the user identity needed by macOS's
// trust backend while excluding every common proxy and alternate-CA variable.
func nativeProbeEnvironment() []string {
	environment := []string{"LANG=C", "LC_ALL=C", "PATH=/usr/bin:/bin"}
	if home := os.Getenv("HOME"); home != "" {
		environment = append(environment, "HOME="+home)
	}
	return environment
}

// validateEndpoints requires the exact three-project proof and rejects any
// spelling that could hide a port, resolver override, URL path, or duplicate.
func validateEndpoints(endpoints []Endpoint) error {
	if len(endpoints) != 3 {
		return fmt.Errorf("trusted HTTPS probe requires exactly three endpoints, got %d", len(endpoints))
	}
	domains := make(map[string]struct{}, len(endpoints))
	titles := make(map[string]struct{}, len(endpoints))
	for _, endpoint := range endpoints {
		if !validProjectTestDomain(endpoint.Domain) {
			return fmt.Errorf("trusted HTTPS domain %q must be one lowercase DNS label beneath .test", endpoint.Domain)
		}
		if endpoint.OpenAPITitle == "" || strings.TrimSpace(endpoint.OpenAPITitle) != endpoint.OpenAPITitle {
			return fmt.Errorf("trusted HTTPS endpoint %q has an invalid OpenAPI title", endpoint.Domain)
		}
		if _, exists := domains[endpoint.Domain]; exists {
			return fmt.Errorf("trusted HTTPS domain %q is duplicated", endpoint.Domain)
		}
		if _, exists := titles[endpoint.OpenAPITitle]; exists {
			return fmt.Errorf("trusted HTTPS OpenAPI title %q is duplicated", endpoint.OpenAPITitle)
		}
		domains[endpoint.Domain] = struct{}{}
		titles[endpoint.OpenAPITitle] = struct{}{}
	}
	return nil
}

// validProjectTestDomain accepts one conventional project slug and no wildcard,
// subdomain, Unicode, underscore, port, trailing dot, or URL syntax.
func validProjectTestDomain(domain string) bool {
	label, found := strings.CutSuffix(domain, ".test")
	if !found || label == "" || len(label) > 63 || strings.Contains(label, ".") || strings.HasPrefix(label, "-") || strings.HasSuffix(label, "-") {
		return false
	}
	for _, character := range label {
		if (character >= 'a' && character <= 'z') || (character >= '0' && character <= '9') || character == '-' {
			continue
		}
		return false
	}
	return true
}

// decodeOpenAPITitle admits only one bounded JSON document containing the
// generated OpenAPI identity needed by the routing assertion.
func decodeOpenAPITitle(body []byte) (string, error) {
	if len(body) == 0 {
		return "", errors.New("OpenAPI response is empty")
	}
	if len(body) > maximumProbeOutputBytes {
		return "", errors.New("OpenAPI response exceeds the acceptance bound")
	}
	var document struct {
		OpenAPI string `json:"openapi"`
		Info    struct {
			Title string `json:"title"`
		} `json:"info"`
	}
	decoder := json.NewDecoder(bytes.NewReader(body))
	if err := decoder.Decode(&document); err != nil {
		return "", err
	}
	if err := requireJSONEnd(decoder); err != nil {
		return "", err
	}
	if strings.TrimSpace(document.OpenAPI) == "" {
		return "", errors.New("OpenAPI response has no version")
	}
	if document.Info.Title == "" || strings.TrimSpace(document.Info.Title) != document.Info.Title {
		return "", errors.New("OpenAPI response has no canonical info.title")
	}
	return document.Info.Title, nil
}

// requireJSONEnd rejects concatenated documents that could make response
// identity depend on which parser a later platform adapter happens to use.
func requireJSONEnd(decoder *json.Decoder) error {
	var trailing any
	err := decoder.Decode(&trailing)
	if errors.Is(err, io.EOF) {
		return nil
	}
	if err == nil {
		return errors.New("OpenAPI response contains trailing JSON")
	}
	return fmt.Errorf("decode trailing OpenAPI response: %w", err)
}

// boundedBuffer drains beyond its retained maximum while recording that the
// response crossed the evidence limit.
type boundedBuffer struct {
	contents bytes.Buffer
	maximum  int
	overflow bool
}

// Write drains the child stream while retaining at most the configured bound.
func (buffer *boundedBuffer) Write(body []byte) (int, error) {
	written := len(body)
	remaining := buffer.maximum - buffer.contents.Len()
	if remaining <= 0 {
		buffer.overflow = buffer.overflow || len(body) > 0
		return written, nil
	}
	if len(body) > remaining {
		buffer.overflow = true
		body = body[:remaining]
	}
	_, _ = buffer.contents.Write(body)
	return written, nil
}

// Bytes returns the retained bounded prefix after process completion.
func (buffer *boundedBuffer) Bytes() []byte {
	return buffer.contents.Bytes()
}
