// Code generated by forj generate --storage. DO NOT EDIT.
// Run: forj generate --storage
//
// These storage manager accessors are derived from the current .env file
// and environment variables available when generation ran.
// Named accessors are generated from STORAGE_<NAME>_<KEY> environment variables.
package storages

import "github.com/goforj/storage"

// Default returns the default storage disk instance derived from STORAGE_* configuration.
func (m *Manager) Default() storage.Storage {
	return m.defaultDisk
}

// Instances returns the generated storage disk instances derived from STORAGE_* configuration.
func (m *Manager) Instances() []Instance {
	instances := []Instance{
		{Name: "default", Driver: m.defaultDriver, Disk: m.defaultDisk, IsDefault: true},
	}
	return instances
}
