// Code generated by GoForj CLI. DO NOT EDIT.

package runtime

import (
	"fmt"
	"strings"

	"github.com/goforj/env/v2"
)

const defaultAppName = "app"

// AppComponents records the component participation compiled for one App.
type AppComponents struct {
	CLI              bool
	DemoApp          bool
	Mail             bool
	Auth             bool
	OAuth            bool
	WebAPI           bool
	WebUI            bool
	Metrics          bool
	Observability    bool
	Grafana          bool
	Docker           bool
	DatabaseMySQL    bool
	DatabasePostgres bool
	DatabaseSQLite   bool
	Scheduler        bool
	Cache            bool
	Jobs             bool
}

// HasDatabase reports whether the App participates in a generated database capability.
func (c AppComponents) HasDatabase() bool {
	return c.DatabaseMySQL || c.DatabasePostgres || c.DatabaseSQLite
}

// AppInfo describes one compiled application and its deterministic runtime defaults.
type AppInfo struct {
	Name        string
	Index       int
	EnvPrefix   string
	HTTPPort    int
	RuntimeBase int
	Components  AppComponents
}

// Apps is generated from the app layout at render time.
var Apps = []AppInfo{
	{
		Name: "app", Index: 0, EnvPrefix: "", HTTPPort: 3000, RuntimeBase: 10000,
		Components: AppComponents{
			CLI:              true,
			DemoApp:          false,
			Mail:             false,
			Auth:             false,
			OAuth:            false,
			WebAPI:           false,
			WebUI:            false,
			Metrics:          false,
			Observability:    false,
			Grafana:          false,
			Docker:           false,
			DatabaseMySQL:    false,
			DatabasePostgres: false,
			DatabaseSQLite:   false,
			Scheduler:        false,
			Cache:            false,
			Jobs:             false,
		},
	},
	{
		Name: "harbord", Index: 1, EnvPrefix: "HARBORD", HTTPPort: 3001, RuntimeBase: 10010,
		Components: AppComponents{
			CLI:              true,
			DemoApp:          false,
			Mail:             false,
			Auth:             false,
			OAuth:            false,
			WebAPI:           false,
			WebUI:            false,
			Metrics:          false,
			Observability:    false,
			Grafana:          false,
			Docker:           false,
			DatabaseMySQL:    false,
			DatabasePostgres: false,
			DatabaseSQLite:   true,
			Scheduler:        false,
			Cache:            false,
			Jobs:             false,
		},
	},
}

// CurrentApp returns the app identity selected for this process.
func CurrentApp() AppInfo {
	return App(env.Get("FORJ_APP", ""))
}

// App returns compiled metadata for name or falls back to the default app.
func App(name string) AppInfo {
	name = strings.TrimSpace(name)
	if name == "" {
		name = strings.TrimSpace(env.Get("FORJ_APP", ""))
	}
	if name == "" {
		name = defaultAppName
	}
	for _, target := range Apps {
		if target.Name == name {
			return target
		}
	}
	if len(Apps) > 0 {
		return Apps[0]
	}
	return AppInfo{Name: defaultAppName, HTTPPort: 3000, RuntimeBase: 10000}
}

// HTTPPort resolves the HTTP listener port for the current app.
func HTTPPort() string {
	return HTTPPortForApp("")
}

// HTTPPortForApp resolves the HTTP listener port for a specific app.
func HTTPPortForApp(target string) string {
	info := App(target)
	keys := appEnvKeys(info, "PORT", "API_HTTP_PORT")
	if info.Name == defaultAppName {
		keys = append(keys, "PORT", "API_HTTP_PORT")
	}
	return firstEnv(keys, fmt.Sprintf("%d", info.HTTPPort))
}

// MetricsPort resolves the shared app/HTTP metrics port for the current app.
func MetricsPort() string {
	return MetricsPortForApp("")
}

// MetricsPortForApp resolves the shared app/HTTP metrics port for a specific app.
func MetricsPortForApp(target string) string {
	info := App(target)
	keys := appEnvKeys(info, "METRICS_PORT", "API_METRICS_PORT", "METRICS_API_PORT")
	if info.Name == defaultAppName {
		keys = append(keys, "METRICS_PORT", "API_METRICS_PORT", "METRICS_API_PORT")
	}
	return firstEnv(keys, fmt.Sprintf("%d", info.RuntimeBase))
}

// SchedulerMetricsPort resolves the scheduler metrics port for the current app.
func SchedulerMetricsPort() string {
	return SchedulerMetricsPortForApp("")
}

// SchedulerMetricsPortForApp resolves the scheduler metrics port for a specific app.
func SchedulerMetricsPortForApp(target string) string {
	info := App(target)
	keys := appEnvKeys(info, "SCHEDULER_METRICS_PORT", "METRICS_SCHEDULER_PORT", "METRICS_PORT")
	if info.Name == defaultAppName {
		keys = append(keys, "SCHEDULER_METRICS_PORT", "METRICS_SCHEDULER_PORT", "METRICS_PORT")
	}
	return firstEnv(keys, fmt.Sprintf("%d", info.RuntimeBase+1))
}

func appEnvKeys(info AppInfo, suffixes ...string) []string {
	if info.EnvPrefix == "" {
		return nil
	}
	keys := make([]string, 0, len(suffixes))
	for _, suffix := range suffixes {
		if suffix = strings.TrimSpace(suffix); suffix != "" {
			keys = append(keys, info.EnvPrefix+"_"+suffix)
		}
	}
	return keys
}

// firstEnv preserves ordered App fallbacks while treating whitespace-only overrides as absent.
func firstEnv(keys []string, fallback string) string {
	for _, key := range keys {
		if value := strings.TrimSpace(env.Get(key, "")); value != "" {
			return value
		}
	}
	return fallback
}
