// Code generated by GoForj CLI. DO NOT EDIT.
// App commands are registered here; place command code in the package that owns the workflow.

package harbordapp

import (
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/harbor/migrations"
)

// RootCmd owns the generated app command surface, including app-local make commands.
type RootCmd struct {
	Commands
	MakeCommandCmd     makecmd.CommandCmd            `cmd:""`
	MakeMigrationCmd   makecmd.MigrationCmd          `cmd:""`
	MakeModelCmd       makecmd.ModelCmd              `cmd:""`
	MigrateCmd         migrations.MigrateCmd         `cmd:""`
	MigrateRollbackCmd migrations.MigrateRollbackCmd `cmd:""`
}

// NewRootCmd assembles framework and app-owned commands on this App's command surface.
func NewRootCmd(
	commands *Commands,
	makeCommandCmd *makecmd.CommandCmd,
	makeMigrationCmd *makecmd.MigrationCmd,
	makeModelCmd *makecmd.ModelCmd,
	migrateCmd *migrations.MigrateCmd,
	migrateRollbackCmd *migrations.MigrateRollbackCmd,
) *RootCmd {
	return &RootCmd{
		Commands:           *commands,
		MakeCommandCmd:     *makeCommandCmd,
		MakeMigrationCmd:   *makeMigrationCmd,
		MakeModelCmd:       *makeModelCmd,
		MigrateCmd:         *migrateCmd,
		MigrateRollbackCmd: *migrateRollbackCmd,
	}
}
