// Code generated by GoForj CLI. DO NOT EDIT.
// Framework-owned manager wiring lives here.

package wire

import (
	"github.com/goforj/harbor/internal/inspects"
	"github.com/goforj/wire"
)

var managerSet = wire.NewSet(
	provideInspectManager,
)

// provideInspectManager owns process-local inspect history independently from App Cache.
func provideInspectManager() *inspects.Manager {
	return inspects.NewManager()
}
