// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/harbor/app"
	"github.com/goforj/harbor/internal/cmd"
	"github.com/goforj/harbor/internal/logger"
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/harbor/internal/runtime"
)

// Injectors from wire.go:

// InitializeApplication initializes the application by providing all the dependencies.
func InitializeApplication() (App, error) {
	appLogger := logger.ProvideAppLogger()
	daemonClient := cmd.NewDaemonClient()
	addCmd := cmd.NewAddCmd(daemonClient)
	removeCmd := cmd.NewRemoveCmd(daemonClient)
	startCmd := cmd.NewStartCmd(daemonClient)
	stopCmd := cmd.NewStopCmd(daemonClient)
	restartCmd := cmd.NewRestartCmd(daemonClient)
	openCmd := cmd.NewOpenCmd(daemonClient)
	logsCmd := cmd.NewLogsCmd(daemonClient)
	doctorCmd := cmd.NewDoctorCmd(daemonClient)
	projectStatusCmd := cmd.NewProjectStatusCmd(daemonClient)
	networkSetupApprovalRunner := provideNetworkSetupApprovalRunner(daemonClient)
	networkResolverSetupApprovalRunner := provideNetworkResolverSetupApprovalRunner(daemonClient)
	networkDataPlaneSetupApprovalRunner := provideNetworkDataPlaneSetupApprovalRunner(daemonClient)
	setupCmd := provideSetupCmd(daemonClient, networkSetupApprovalRunner, networkResolverSetupApprovalRunner, networkDataPlaneSetupApprovalRunner)
	resourcesCmd := cmd.NewResourcesCmd()
	aboutCmd := cmd.NewAboutCmd()
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	daemonStatusCmd := cmd.NewDaemonStatusCmd(daemonClient)
	daemonStopCmd := cmd.NewDaemonStopCmd(daemonClient)
	daemonSnapshotCmd := cmd.NewDaemonSnapshotCmd(daemonClient)
	daemonCmd := cmd.NewDaemonCmd(daemonStatusCmd, daemonStopCmd, daemonSnapshotCmd)
	commands := app.NewCommands(addCmd, removeCmd, startCmd, stopCmd, restartCmd, openCmd, logsCmd, doctorCmd, projectStatusCmd, setupCmd, resourcesCmd, aboutCmd, helloWorldCmd, daemonCmd)
	commandCmd := makecmd.NewCommandCmd()
	migrationCmd := makecmd.NewMigrationCmd()
	rootCmd := app.NewRootCmd(commands, commandCmd, migrationCmd)
	timeouts := runtime.NewTimeouts()
	lifecycleRegistry := app.NewLifecycleRegistry()
	manager := provideInspectManager()
	wireApp := NewApplication(appLogger, rootCmd, timeouts, lifecycleRegistry, manager)
	return wireApp, nil
}
