// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/harbor/app"
	"github.com/goforj/harbor/internal/cmd"
	"github.com/goforj/harbor/internal/logger"
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/harbor/internal/runtime"
)

// Injectors from wire.go:

// InitializeApplication initializes the application by providing all the dependencies.
func InitializeApplication() (App, error) {
	appLogger := logger.ProvideAppLogger()
	resourcesCmd := cmd.NewResourcesCmd()
	aboutCmd := cmd.NewAboutCmd()
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	commands := app.NewCommands(resourcesCmd, aboutCmd, helloWorldCmd)
	commandCmd := makecmd.NewCommandCmd()
	migrationCmd := makecmd.NewMigrationCmd()
	rootCmd := app.NewRootCmd(commands, commandCmd, migrationCmd)
	timeouts := runtime.NewTimeouts()
	lifecycleRegistry := app.NewLifecycleRegistry()
	manager := provideInspectManager()
	wireApp := NewApplication(appLogger, rootCmd, timeouts, lifecycleRegistry, manager)
	return wireApp, nil
}
