// Code generated by GoForj CLI. DO NOT EDIT.
// Framework-owned application assembly lives here; add app providers in the app-owned injectors.

package wire

import (
	"context"
	"fmt"
	"os"
	"strings"
	"syscall"
	"time"

	"github.com/alecthomas/kong"

	"github.com/goforj/harbor/app/harbord"
	"github.com/goforj/harbor/internal/cmd"
	"github.com/goforj/harbor/internal/inspects"
	"github.com/goforj/harbor/internal/konghelp"
	"github.com/goforj/harbor/internal/logger"
	"github.com/goforj/harbor/internal/runtime"
)

// App is the root App resource
type App struct {
	rootCmd     *harbordapp.RootCmd
	logger      *logger.AppLogger
	inspects    *inspects.Manager
	lifecycle   *runtime.Lifecycle
	appTimeouts *runtime.Timeouts
}

// RootCmd returns the root command of the application
func (a *App) RootCmd() *harbordapp.RootCmd {
	return a.rootCmd
}

// Logger returns the logger of the application
func (a *App) Logger() *logger.AppLogger {
	return a.logger
}

// Inspects returns the app inspect manager.
func (a *App) Inspects() *inspects.Manager {
	return a.inspects
}

// Lifecycle returns the app lifecycle manager so callers can register custom hooks.
func (a *App) Lifecycle() *runtime.Lifecycle {
	return a.lifecycle
}

// Startup initializes background app resources.
func (a *App) Startup(ctx context.Context) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if runtime.SourceFromContext(ctx) == "" {
		ctx = runtime.WithSource(ctx, runtime.SourceStartup)
	}
	startedInspect := false
	if inspects.RecorderFromContext(ctx) == nil {
		ctx = a.inspects.Begin(ctx, runtime.SourceStartup, "startup", map[string]string{
			"phase": "startup",
		})
		startedInspect = true
	}
	if err := a.lifecycle.Start(ctx); err != nil {
		if startedInspect {
			a.inspects.Finish(ctx, "error", err)
		}
		return err
	}
	if startedInspect {
		a.inspects.Finish(ctx, "ok", nil)
	}
	return nil
}

// Shutdown gracefully releases background app resources.
func (a *App) Shutdown(ctx context.Context) error {
	return a.lifecycle.Stop(ctx)
}

// Run starts app lifecycle, executes CLI args, and performs graceful shutdown.
func (a *App) Run(ctx context.Context, args []string) error {
	if ctx == nil {
		ctx = context.Background()
	}
	command := ""
	if len(args) > 0 {
		command = args[0]
	}
	origin := strings.TrimSpace(os.Getenv("FORJ_COMMAND_ORIGIN"))
	parser, err := kong.New(
		a.RootCmd(),
		kong.Name(cmd.AppHelpName()),
		kong.Help(konghelp.GuidedFormatter),
	)
	if err != nil {
		return err
	}

	if len(args) == 0 {
		parseCtx, _ := parser.Parse([]string{"--help"})
		parseCtx.PrintUsage(false)
		return nil
	}

	parseCtx, err := parser.Parse(args)
	if err != nil {
		return konghelp.CommandParseError(parser, command, err)
	}
	ctx, stop := runtime.CLINotifyContext(ctx, syscall.SIGINT, syscall.SIGTERM)
	defer stop()
	ctx = a.inspects.Begin(ctx, runtime.SourceCLI, command, map[string]string{
		"command": command,
	})
	parseCtx.BindTo(ctx, (*context.Context)(nil))
	shutdownTimeout := a.shutdownTimeoutForOrigin(origin)
	if err := a.Startup(ctx); err != nil {
		a.inspects.Finish(ctx, "error", err)
		return err
	}
	defer func() {
		a.shutdownAfterRun(command, args, origin, shutdownTimeout)
		a.inspects.Finish(ctx, "", nil)
	}()
	if err := parseCtx.Run(); err != nil {
		a.inspects.Finish(ctx, "error", err)
		return err
	}
	a.inspects.Finish(ctx, "ok", nil)
	return nil
}

// shutdownAfterRun centralizes deferred shutdown so command completion and inspect finalization stay ordered.
func (a *App) shutdownAfterRun(command string, args []string, origin string, timeout time.Duration) {
	shutdownCtx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	if err := a.Shutdown(shutdownCtx); err != nil {
		a.logShutdownError(err, command, args, origin, timeout)
	}
}

// logShutdownError includes subprocess and origin context that would be lost at the call site.
func (a *App) logShutdownError(err error, command string, args []string, origin string, timeout time.Duration) {
	if origin == "" {
		origin = "cli"
	}
	subprocess := strings.TrimSpace(os.Getenv("FORJ_SUBPROCESS")) == "1"
	msg := "Application shutdown failed"
	if subprocess {
		msg = "Application subprocess shutdown failed"
	}
	a.logger.Error().
		Err(err).
		Str("command", command).
		Strs("args", args).
		Str("origin", origin).
		Bool("subprocess", subprocess).
		Int("pid", os.Getpid()).
		Dur("shutdown_timeout", timeout).
		Msg(msg)
}

// NewApplication creates a new App instance
func NewApplication(
	appLogger *logger.AppLogger,
	rootCmd *harbordapp.RootCmd,
	appTimeouts *runtime.Timeouts,
	lifecycleRegistry *harbordapp.LifecycleRegistry,
	inspectManager *inspects.Manager,
) App {
	lifecycleManager := runtime.NewLifecycle(appTimeouts)

	attachInspectLogSink(appLogger, inspectManager)
	lifecycleRegistry.Register(lifecycleManager)

	return App{
		rootCmd:     rootCmd,
		logger:      appLogger,
		inspects:    inspectManager,
		lifecycle:   lifecycleManager,
		appTimeouts: appTimeouts,
	}
}

// attachInspectLogSink mirrors logs with inspect IDs into the inspect timeline.
func attachInspectLogSink(appLogger *logger.AppLogger, inspectManager *inspects.Manager) {
	appLogger.AddSink(func(entry logger.LogEntry) {
		inspectID := strings.TrimSpace(fmt.Sprintf("%v", entry.Fields["inspect_id"]))
		if inspectID == "" {
			return
		}
		fields := make(map[string]any, len(entry.Fields))
		for key, value := range entry.Fields {
			if key == "inspect_id" {
				continue
			}
			fields[key] = value
		}
		inspectManager.RecordLog(inspects.WithInspectID(context.Background(), inspectID), inspects.LogInspectEvent{
			Level:   entry.Level,
			Message: entry.Message,
			Fields:  fields,
		})
	})
}

// shutdownTimeoutForOrigin gives scheduler subprocesses a shorter shutdown window than the parent runtime.
func (a *App) shutdownTimeoutForOrigin(origin string) time.Duration {
	if strings.EqualFold(origin, "scheduler_command") {
		return a.appTimeouts.SchedulerSubprocessShutdownTimeout()
	}
	return a.appShutdownTimeout()
}

// appShutdownTimeout keeps the public shutdown policy behind the app timeout configuration.
func (a *App) appShutdownTimeout() time.Duration {
	return a.appTimeouts.ShutdownTimeout()
}
