// Code generated by GoForj CLI. DO NOT EDIT.
// Framework-owned application assembly tests live here.

package wire

import (
	"context"
	"errors"
	"github.com/goforj/harbor/internal/runtime"
	"sync/atomic"
	"testing"
)

func TestAppStartupIsIdempotent(t *testing.T) {
	var calls atomic.Int64
	manager := runtime.NewLifecycle(runtime.NewTimeouts())
	manager.On(runtime.Startup, func(context.Context) error {
		calls.Add(1)
		return nil
	})

	app := App{lifecycle: manager}
	if err := app.Startup(context.Background()); err != nil {
		t.Fatalf("first startup failed: %v", err)
	}
	if err := app.Startup(context.Background()); err != nil {
		t.Fatalf("second startup failed: %v", err)
	}
	if got := calls.Load(); got != 1 {
		t.Fatalf("expected startup hook to run once, got %d", got)
	}
}

func TestAppShutdownIsIdempotent(t *testing.T) {
	var calls atomic.Int64
	manager := runtime.NewLifecycle(runtime.NewTimeouts())
	manager.On(runtime.Shutdown, func(context.Context) error {
		calls.Add(1)
		return nil
	})

	app := App{lifecycle: manager}
	if err := app.Startup(context.Background()); err != nil {
		t.Fatalf("startup failed: %v", err)
	}
	if err := app.Shutdown(context.Background()); err != nil {
		t.Fatalf("first shutdown failed: %v", err)
	}
	if err := app.Shutdown(context.Background()); err != nil {
		t.Fatalf("second shutdown failed: %v", err)
	}
	if got := calls.Load(); got != 1 {
		t.Fatalf("expected shutdown hook to run once, got %d", got)
	}
}

func TestAppShutdownAggregatesErrors(t *testing.T) {
	errA := errors.New("shutdown-a")
	errB := errors.New("shutdown-b")

	manager := runtime.NewLifecycle(runtime.NewTimeouts())
	manager.On(runtime.Shutdown, func(context.Context) error { return errA })
	manager.On(runtime.Shutdown, func(context.Context) error { return errB })

	app := App{lifecycle: manager}
	if err := app.Startup(context.Background()); err != nil {
		t.Fatalf("startup failed: %v", err)
	}

	err := app.Shutdown(context.Background())
	if err == nil {
		t.Fatal("expected aggregated shutdown error")
	}
	if !errors.Is(err, errA) {
		t.Fatalf("expected error to include %v, got %v", errA, err)
	}
	if !errors.Is(err, errB) {
		t.Fatalf("expected error to include %v, got %v", errB, err)
	}
}
