// Code generated by GoForj CLI. DO NOT EDIT.
// Framework-owned database wiring lives here; add repositories in inject_repositories_app.go.

package wire

import (
	"github.com/goforj/harbor/internal/database"
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/harbor/migrations"

	"github.com/goforj/wire"
)

// databaseSet is a wire set that provides the database connection.
var databaseSet = wire.NewSet(
	database.NewConnections,
	makecmd.NewModelCmd,
	migrations.NewMigrateCmd,
	migrations.NewMigrateRollbackCmd,
	repositorySet,
)
