// Code generated by GoForj CLI. DO NOT EDIT.
// Framework-owned command wiring lives here; add application commands in inject_cmd_app.go.

package wire

import (
	"github.com/goforj/harbor/app/harbord"
	"github.com/goforj/harbor/internal/cmd"
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/wire"
)

// cmdSet is a wire set that provides framework command wiring.
var cmdSet = wire.NewSet(
	appCommandSet,
	harbordapp.NewCommands,
	harbordapp.NewRootCmd,
	cmd.NewAboutCmd,
	makecmd.NewCommandCmd,
	makecmd.NewMigrationCmd,
)
