// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/harbor/app/harbord"
	"github.com/goforj/harbor/internal/authority"
	"github.com/goforj/harbor/internal/cmd"
	"github.com/goforj/harbor/internal/daemon"
	"github.com/goforj/harbor/internal/database"
	"github.com/goforj/harbor/internal/harbordruntime"
	"github.com/goforj/harbor/internal/logger"
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/harbor/internal/models"
	"github.com/goforj/harbor/internal/projectprocess"
	"github.com/goforj/harbor/internal/reconcile"
	"github.com/goforj/harbor/internal/runtime"
	"github.com/goforj/harbor/internal/state"
	"github.com/goforj/harbor/migrations"
)

// Injectors from wire.go:

// InitializeApplication initializes the application by providing all the dependencies.
func InitializeApplication(environment projectprocess.Environment) (App, error) {
	manager := provideInspectManager()
	connections := database.NewConnections(manager)
	appLogger := logger.ProvideAppLogger()
	resourcesCmd := cmd.NewResourcesCmd()
	aboutCmd := cmd.NewAboutCmd()
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	harborStateRepo := models.NewHarborStateRepo(connections)
	projectRepo := models.NewProjectRepo(connections)
	projectSessionRepo := models.NewProjectSessionRepo(connections)
	networkStateRepo := models.NewNetworkStateRepo(connections)
	mutationCoordinator := state.NewMutationCoordinator(connections)
	store := state.NewStore(harborStateRepo, projectRepo, projectSessionRepo, networkStateRepo, mutationCoordinator)
	operationRepo := models.NewOperationRepo(connections)
	operationTransitionRepo := models.NewOperationTransitionRepo(connections)
	operationJournal := state.NewOperationJournal(connections, operationRepo, operationTransitionRepo, harborStateRepo, mutationCoordinator)
	helperApprovalPlanRepo := models.NewHelperApprovalPlanRepo(connections)
	helperApprovalPlanSource := state.NewHelperApprovalPlanSource(helperApprovalPlanRepo)
	machineOwnershipProjectionRepo := models.NewMachineOwnershipProjectionRepo(connections)
	machineOwnershipProjectionSource := state.NewMachineOwnershipProjectionSource(machineOwnershipProjectionRepo)
	controller, err := harbordruntime.NewController(store, operationJournal)
	if err != nil {
		return App{}, err
	}
	projectUnregisterCoordinator, err := provideProjectUnregisterCoordinator(store, operationJournal, helperApprovalPlanSource, machineOwnershipProjectionSource, controller)
	if err != nil {
		return App{}, err
	}
	supervisor := provideProjectProcessSupervisor(environment)
	goforjruntimeRuntime := provideGoForjProjectRuntime(supervisor)
	projectLifecycleCoordinator := reconcile.NewProjectLifecycleCoordinator(store, operationJournal, goforjruntimeRuntime, controller)
	networkSetupPlanRepo := models.NewNetworkSetupPlanRepo(connections)
	networkSetupPlanSource := state.NewNetworkSetupPlanSource(networkSetupPlanRepo)
	networkSetupCoordinator, err := provideNetworkSetupCoordinator(store, operationJournal, networkSetupPlanSource, machineOwnershipProjectionSource)
	if err != nil {
		return App{}, err
	}
	networkResolverSetupPlanRepo := models.NewNetworkResolverSetupPlanRepo(connections)
	networkResolverSetupPlanSource := state.NewNetworkResolverSetupPlanSource(networkResolverSetupPlanRepo)
	networkResolverSetupResolverObserver := provideNetworkResolverObserver()
	networkResolverSetupCoordinator, err := provideNetworkResolverSetupCoordinator(store, operationJournal, networkResolverSetupPlanSource, machineOwnershipProjectionSource, controller, networkResolverSetupResolverObserver)
	if err != nil {
		return App{}, err
	}
	authorityAuthority := authority.NewAuthority(store, projectUnregisterCoordinator, projectLifecycleCoordinator, networkSetupCoordinator, networkResolverSetupCoordinator, controller)
	wireNetworkDataPlaneSetupCapability, err := provideNetworkDataPlaneSetupCapability(networkStateRepo, operationJournal, store, machineOwnershipProjectionSource, controller, projectLifecycleCoordinator)
	if err != nil {
		return App{}, err
	}
	wireNetworkReleaseCapability, err := provideNetworkReleaseCapability(networkStateRepo, operationJournal, store, machineOwnershipProjectionSource, controller, networkResolverSetupResolverObserver)
	if err != nil {
		return App{}, err
	}
	networkResolverPolicyMigrationPlanRepo := models.NewNetworkResolverPolicyMigrationPlanRepo(connections)
	networkResolverPolicyMigrationPlanSource := state.NewNetworkResolverPolicyMigrationPlanSource(networkResolverPolicyMigrationPlanRepo)
	wireNetworkResolverPolicyMigrationCapability, err := provideNetworkResolverPolicyMigrationCapability(operationJournal, store, networkResolverPolicyMigrationPlanSource, machineOwnershipProjectionSource, controller, networkResolverSetupResolverObserver)
	if err != nil {
		return App{}, err
	}
	shutdown := daemon.NewShutdown()
	server, err := provideControlServer(authorityAuthority, wireNetworkDataPlaneSetupCapability, wireNetworkReleaseCapability, wireNetworkResolverPolicyMigrationCapability, shutdown, appLogger)
	if err != nil {
		return App{}, err
	}
	readinessCheck, err := provideHarbordReadiness(connections)
	if err != nil {
		return App{}, err
	}
	runner, err := provideDaemonRunner(server, readinessCheck, controller, projectUnregisterCoordinator, projectLifecycleCoordinator, operationJournal, wireNetworkDataPlaneSetupCapability, wireNetworkReleaseCapability, shutdown)
	if err != nil {
		return App{}, err
	}
	commands := harbordapp.NewCommands(resourcesCmd, aboutCmd, helloWorldCmd, runner)
	commandCmd := makecmd.NewCommandCmd()
	migrationCmd := makecmd.NewMigrationCmd()
	modelCmd := makecmd.NewModelCmd(connections)
	migrateCmd := migrations.NewMigrateCmd(appLogger, connections)
	migrateRollbackCmd := migrations.NewMigrateRollbackCmd(appLogger, connections)
	rootCmd := harbordapp.NewRootCmd(commands, commandCmd, migrationCmd, modelCmd, migrateCmd, migrateRollbackCmd)
	timeouts := runtime.NewTimeouts()
	lifecycleRegistry := harbordapp.NewLifecycleRegistry()
	app := NewApplication(connections, appLogger, rootCmd, timeouts, lifecycleRegistry, manager)
	return app, nil
}
