// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/goforj/harbor/app/harbord"
	"github.com/goforj/harbor/internal/authority"
	"github.com/goforj/harbor/internal/cmd"
	"github.com/goforj/harbor/internal/database"
	"github.com/goforj/harbor/internal/harbordruntime"
	"github.com/goforj/harbor/internal/logger"
	"github.com/goforj/harbor/internal/makecmd"
	"github.com/goforj/harbor/internal/models"
	"github.com/goforj/harbor/internal/runtime"
	"github.com/goforj/harbor/internal/state"
	"github.com/goforj/harbor/migrations"
)

// Injectors from wire.go:

// InitializeApplication initializes the application by providing all the dependencies.
func InitializeApplication() (App, error) {
	manager := provideInspectManager()
	connections := database.NewConnections(manager)
	appLogger := logger.ProvideAppLogger()
	resourcesCmd := cmd.NewResourcesCmd()
	aboutCmd := cmd.NewAboutCmd()
	helloWorldCmd := cmd.NewHelloWorldCmd(appLogger)
	harborStateRepo := models.NewHarborStateRepo(connections)
	projectRepo := models.NewProjectRepo(connections)
	networkStateRepo := models.NewNetworkStateRepo(connections)
	mutationCoordinator := state.NewMutationCoordinator(connections)
	store := state.NewStore(harborStateRepo, projectRepo, networkStateRepo, mutationCoordinator)
	authorityAuthority := authority.NewAuthority(store)
	server, err := provideControlServer(authorityAuthority)
	if err != nil {
		return App{}, err
	}
	readinessCheck, err := provideHarbordReadiness(connections)
	if err != nil {
		return App{}, err
	}
	controller, err := harbordruntime.NewController(store)
	if err != nil {
		return App{}, err
	}
	runner, err := provideDaemonRunner(server, readinessCheck, controller)
	if err != nil {
		return App{}, err
	}
	commands := harbordapp.NewCommands(resourcesCmd, aboutCmd, helloWorldCmd, runner)
	commandCmd := makecmd.NewCommandCmd()
	migrationCmd := makecmd.NewMigrationCmd()
	modelCmd := makecmd.NewModelCmd(connections)
	migrateCmd := migrations.NewMigrateCmd(appLogger, connections)
	migrateRollbackCmd := migrations.NewMigrateRollbackCmd(appLogger, connections)
	rootCmd := harbordapp.NewRootCmd(commands, commandCmd, migrationCmd, modelCmd, migrateCmd, migrateRollbackCmd)
	timeouts := runtime.NewTimeouts()
	lifecycleRegistry := harbordapp.NewLifecycleRegistry()
	app := NewApplication(connections, appLogger, rootCmd, timeouts, lifecycleRegistry, manager)
	return app, nil
}
